version: '3.9'
services:
  ibge-adapter:
    container_name: ibge-adapter
    depends_on:
      - redis-cache
    restart: always
    build:
      context: ./ibge-adapter-launcher
    image: ibge-adapter:latest
    environment:
      REDIS_HOST: redis-cache
    ports:
      - "8080:8080"
  redis-cache:
    container_name: redis-cache
    image: redis:latest
    ports:
      - "6379:6379"